---
- name: <vagrant> | Add Vagrant to sudoers
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: 'vagrant ALL=NOPASSWD: ALL'
    state: present

- name: <vagrant> | Copy RSA key to .ssh
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/home/vagrant/.ssh/{{ item | basename }}"
    owner: vagrant
    group: vagrant
    mode: '0600'
  with_items: 
    - "files/id_ed25519.pub"
    - "files/id_ed25519"

- name: <vagrant> | Add RSA key to authorized_keys
  ansible.builtin.shell: cat /home/vagrant/.ssh/id_ed25519.pub >> /home/vagrant/.ssh/authorized_keys

- name: <os> | Disallow SSH password authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
    validate: "/usr/sbin/sshd -t -f %s"
  notify:
    - Restart SSH

- name: <os> | Install dependencies
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ bluebanquise_packages_to_install }}"

- name: <bluebanquise> | Online Bootstrap
  ansible.builtin.shell: "curl -o online_bootstrap.sh https://raw.githubusercontent.com/bluebanquise/bluebanquise/master/bootstrap/online_bootstrap.sh && chmod +x online_bootstrap.sh && sudo ./online_bootstrap.sh --silent"
  
- name: <bluebanquise> | Create BlueBanquise inventory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items: "{{ bluebanquise_inventory_structure }}"

- name: <bluebanquise> | Copy bb_core.yml to inventory
  ansible.builtin.shell: cp "{{ bluebanquise_main_directory }}/resources/bb_core.yml" "{{ bluebanquise_inventory_directory }}/group_vars/all/bb_core.yml"

- name: <bluebanquise> | Copy nodes.yml to inventory
  ansible.builtin.copy:
    src: "files/nodes.yml"
    dest: "{{ bluebanquise_inventory_directory }}/cluster/nodes/nodes.yml"

- name: <bluebanquise> | Copy groups.yml to inventory
  ansible.builtin.copy:
    src: "files/groups.yml"
    dest: "{{ bluebanquise_inventory_directory }}/cluster/groups/groups.yml"

- name: <bluebanquise> | Create fn inventory
  ansible.builtin.copy:
    src: "files/fn"
    dest: "{{ bluebanquise_inventory_directory }}/cluster/groups/fn"

- name: <bluebanquise> | Create hw inventory
  ansible.builtin.copy:
    src: "files/hw"
    dest: "{{ bluebanquise_inventory_directory }}/cluster/groups/hw"

- name: <bluebanquise> | Create os inventory
  ansible.builtin.copy:
    src: "files/os"
    dest: "{{ bluebanquise_inventory_directory }}/cluster/groups/os"

- name: <bluebanquise> | Copy networks.yml to inventory
  ansible.builtin.copy:
    src: "files/networks.yml"
    dest: "{{ bluebanquise_inventory_directory }}/group_vars/all/networks.yml"

- name: <bluebanquise> | Copy global.yml to inventory
  ansible.builtin.copy:
    src: "files/global.yml"
    dest: "{{ bluebanquise_inventory_directory }}/group_vars/all/global.yml"

- name: <bluebanquise> | Copy repositories.yml to inventory
  ansible.builtin.copy:
    src: "files/repositories.yml"
    dest: "{{ bluebanquise_inventory_directory }}/group_vars/all/repositories.yml"

- name: <bluebanquise> | Create OS inventory
  ansible.builtin.file:
    path: "{{ bluebanquise_inventory_directory }}/group_vars/{{ ansible_distribution_version }}"
    state: directory
    mode: '0755'

- name: <bluebanquise> | Copy settings.yml to OS inventory
  ansible.builtin.copy:
    src: "files/settings.yml"
    dest: "{{ bluebanquise_inventory_directory }}/group_vars/{{ ansible_distribution_version }}/settings.yml"

- name: <bluebanquise> | Create playbooks directory
  ansible.builtin.file:
    path: "{{ bluebanquise_main_directory }}/playbooks"
    state: directory
    mode: '0755'
  
- name: <bluebanquise> | Copy managements.yml playbooks
  ansible.builtin.copy:
    src: "files/managements.yml"
    dest: "{{ bluebanquise_main_directory }}/playbooks/managements.yml"