---
- name: <vagrant> | Add Vagrant to sudoers
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: 'vagrant ALL=NOPASSWD: ALL'
    state: present

- name: <vagrant> | Copy RSA key to .ssh
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/home/vagrant/.ssh/{{ item | basename }}"
    owner: vagrant
    group: vagrant
    mode: '0600'
  with_items: 
    - "files/id_ed25519.pub"
    - "files/id_ed25519"

- name: <vagrant> | Add RSA key to authorized_keys
  ansible.builtin.shell: cat /home/vagrant/.ssh/id_ed25519.pub >> /home/vagrant/.ssh/authorized_keys

- name: <os> | Install dependencies
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ bluebanquise_packages_to_install }}"

- name: <bluebanquise> | Online Bootstrap
  ansible.builtin.shell: "curl -o online_bootstrap.sh https://raw.githubusercontent.com/bluebanquise/bluebanquise/master/bootstrap/online_bootstrap.sh && chmod +x online_bootstrap.sh && sudo ./online_bootstrap.sh --silent"
  
- name: <bluebanquise> | Create BlueBanquise inventory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items: "{{ bluebanquise_inventory_structure }}"

- name: <bluebanquise> | Copy bb_core.yml to inventory
  ansible.builtin.shell: cp "{{ bluebanquise_install_dir }}/resources/bb_core.yml" "{{ bluebanquise_inventory_directory }}/group_vars/all/bb_core.yml"

- name: <bluebanquise> | Copy nodes.yml to inventory
  ansible.builtin.copy:
    src: "files/nodes.yml"
    dest: "{{ bluebanquise_inventory_directory }}/cluster/nodes/nodes.yml"

- name: <bluebanquise> | Copy groups.yml to inventory
  ansible.builtin.copy:
    src: "files/groups.yml"
    dest: "{{ bluebanquise_inventory_directory }}/cluster/groups/groups.yml"

- name: <bluebanquise> | Copy repositories.yml to inventory
  ansible.builtin.copy:
    src: "files/repositories.yml"
    dest: "{{ bluebanquise_inventory_directory }}/group_vars/all/repositories.yml"

- name: <bluebanquise> | Copy global.yml to inventory
  ansible.builtin.copy:
    src: "files/global.yml"
    dest: "{{ bluebanquise_inventory_directory }}/group_vars/all/global.yml"

- name: <bluebanquise> | Copy networks.yml to inventory
  ansible.builtin.copy:
    src: "files/global.yml"
    dest: "{{ bluebanquise_inventory_directory }}/group_vars/all/networks.yml"
